CREATE TABLE IF NOT EXISTS trades
(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    user_id uuid REFERENCES users (id) ON DELETE CASCADE,
	instrument TEXT NOT NULL,
	action TEXT NOT NULL,
	quantity INTEGER NOT NULL,
	price REAL NOT NULL,
	time DOUBLE PRECISION NOT NULL,
	commission REAL,
	account_display_name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
