CREATE TABLE IF NOT EXISTS accounts
(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name TEXT NOT NULL UNIQUE,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    sim BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_accounts_userid
ON accounts(user_id);
