CREATE TABLE IF NOT EXISTS executions
(
	id BIGSERIAL NOT NULL PRIMARY KEY,
	trade_id BIGSERIAL references trades (id) ON DELETE CASCADE,
	time DOUBLE PRECISION NOT NULL,
	commission REAL,
	price REAL NOT NULL,
	action TEXT NOT NULL,
	quantity INTEGER NOT NULL,
	instrument TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
