name: CI/CD Pipeline for Traders

on:
  push:
    branches:
      - master # or the name of your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        key: sqlx

    - name: Build
      run: cargo build --release

    - name: Deploy to VPS
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        SERVER="${SERVER_USER}@${SERVER_IP}"
        mkdir -p ~/.ssh/
        echo "$DEPLOY_SSH_KEY" > ~/.ssh/traders-deploy
        chmod 600 ~/.ssh/traders-deploy
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        # Deploy static files
        scp -i ~/.ssh/traders-deploy -r static/ $SERVER:/home/jhg/workspace/traders/
        ssh -i ~/.ssh/traders-deploy $SERVER 'sudo systemctl stop traders'
        # migrations (Split this up into it's own name later
        ssh -i ~/.ssh/traders-deploy $SERVER "DATABASE_URL=${DATABASE_URL} sqlx migrate run"
        # Deploy Traders binary
        scp -i ~/.ssh/traders-deploy target/release/traders $SERVER:/home/jhg/workspace/traders/target/release/traders
        ssh -i ~/.ssh/traders-deploy $SERVER 'sudo systemctl start traders'

