name: CI/CD Pipeline for Traders

on:
  push:
    branches:
      - master # or the name of your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        key: sqlx

    - name: Instal sqlx DB
      run: cargo install sqlx-cli --no-default-features --features native-tls,postgres
    
    - name: Migrate DB
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        SERVER="${SERVER_USER}@${SERVER_IP}"
        mkdir -p ~/.ssh/
        echo "$DEPLOY_SSH_KEY" > ~/.ssh/traders-deploy
        chmod 600 ~/.ssh/traders-deploy
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        ssh -i ~/.ssh/traders-deploy $SERVER 'sqlx migrate run'
        ssh -i ~/.ssh/traders-deploy $SERVER 'cargo sqlx prepare'

    - name: Build
      run: cargo build --release

    - name: Deploy to VPS
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        SERVER="${SERVER_USER}@${SERVER_IP}"
        mkdir -p ~/.ssh/
        echo "$DEPLOY_SSH_KEY" > ~/.ssh/traders-deploy
        chmod 600 ~/.ssh/traders-deploy
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        # Deploy static files
        scp -i ~/.ssh/traders-deploy -r static/ $SERVER:/home/jhg/workspace/traders/
        # Deploy migrations
        scp -i ~/.ssh/traders-deploy -r migrations/ $SERVER:/home/jhg/workspace/traders/
        # Stop service
        ssh -i ~/.ssh/traders-deploy $SERVER 'sudo systemctl stop traders'
        # Deploy Traders binary
        scp -i ~/.ssh/traders-deploy target/release/traders $SERVER:/home/jhg/workspace/traders/target/release/traders
        # Start service
        ssh -i ~/.ssh/traders-deploy $SERVER 'sudo systemctl start traders'

